version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "step-function-test-swager"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dmilqmhl18xv"
s3_prefix = "step-function-test-swager"
region = "us-east-1"
profile = "pablo"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "OpenAPIS3File=\"./openapi.yaml\""
