version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "pablo-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lu8aiqjbh820"
s3_prefix = "pablo-test"
region = "sa-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

