name: Back Actions
on:
  push:
    branches:
      - dev/step-swager
  pull_request:
    branches: 
      - main/step-swager
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Deploy
        uses: tkt-actions/aws-sam-cli@v1
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      - run: |
  
          export "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
          export "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
          echo $PWD
          ./deploy_step.sh step-function-${GITHUB_REF##*/}